name: Update Pilot Jobs

on:
  schedule:
    - cron: "0 7 * * *"   # daily at 07:00 UTC (~12:00 AM Phoenix)
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: python scraper.py

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
