name: Update Pilot Jobs

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  update-jobs:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✅ allow push to repo

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0   # ensures full history for commits

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push updated jobs
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add jobs.json jobs_history.json
        git commit -m "Update jobs.json [skip ci]" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
